version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DATABASE_URL=jdbc:mysql://mysql:3306/anime_db
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
      - PORT=8080

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=anime_db
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
